---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=0 #1000为默认用户可能读取不到其他docker目录,设置0为管理员
      - PGID=0
    volumes:
      - /vol1/1001/docker/syncthing/backup_by_duplicati:/var/syncthing/backup_by_duplicati
      - /vol1/1001/docker/syncthing/other_transfer_in:/var/syncthing/other_transfer_in
    #ports:
     # - 8384:8384 # Web UI
     # - 22000:22000/tcp # TCP file transfers
     # - 22000:22000/udp # QUIC file transfers
     # - 21027:21027/udp # Receive local discovery broadcasts
    network_mode: "host"    #主机模式.无需预先映射端口
    restart: unless-stopped