version: '3.8'
services:
  xunlei:
    image: registry.fnnas.com/fnapp/cnk3x_xunlei:latest
    container_name: xunlei
 #   restart: unless-stopped
    privileged: true
    environment:
      UID: ${TRIM_UID}
      GID: ${TRIM_GID}
      XL_DASHBOARD_USERNAME: ${wizard_username}
      XL_DASHBOARD_PASSWORD: ${wizard_password}    
    volumes:
      - /var/apps/docker-xunlei/target/data:/xunlei/data
      - /vol3/1001/Download/Thunder:/xunlei/downloads
    ports:
      - "2345:2345"
    networks:
      - trim-default
networks:
  trim-default:
    external: true